classbvs/classbvs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from class1 import views
from class2 import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('class/', views.Hello.as_view()),
    path('classt/', views.HelloT.as_view()),
    url(r'^$', v.BookListView.as_view(), name='books'),
    url(r'^(?P<pk>\d+)/$', v.BookDetail.as_view(), name='detail'),
    path('create/', v.BookCreate.as_view()),
    url(r'^update/(?P<pk>\d+)/$', v.BookUpdate.as_view()),
    url(r'^delete/(?P<pk>\d+)/$', v.BookDelete.as_view()),


]

classbvs/class1/models.py
from django.db import models

# Create your models here.

classbvs/class2/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    pages = models.PositiveIntegerField()
    price = models.FloatField()

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

classbvs/testapp/models.py
from django.db import models

# Create your models here.


class Company(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    ceo = models.CharField(max_length=50)

classbvs/class1/views.py
#from django.shortcuts import render
from django.views.generic import View, TemplateView
from django.http import HttpResponse
# Create your views here.


class Hello(View):
    def get(self, request):
        return HttpResponse('<h1>HEllo World This is from class BAsead views</h1>')


class HelloT(TemplateView):
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = 'Gova'
        context['city'] = 'Sathandlahalli'
        context['marks'] = 100
        context['subject'] = 'Python'
        return context

classbvs/class2/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, DeleteView, CreateView
from class2.models import Book
from django.urls import reverse_lazy
# Create your views here.


class BookListView(ListView):
    model = Book
    #template_name = 'book_list.html'
    context_object_name = 'list_of_books'
    # defalt template = book_list.html
    # defalt context object = book_list


class BookDetail(DetailView):
    model = Book
    #template_name = 'book_detail.html'
    # defalt template = book_detail.html
    # defalt context object = book or object


class BookCreate(CreateView):
    model = Book
    fields = ('title', 'author', 'pages', 'price')
    #template_name = 'book_form.html'


class BookUpdate(UpdateView):
    model = Book
    fields = ('title', 'pages', 'price')
    #template_name = 'book_form.html'


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

classbvs/testapp/views.py
from django.shortcuts import render
from testapp.models import Company
from django.views.generic import ListView, DetailView, DeleteView, UpdateView
# Create your views here.

class

classbvs/templates/class2/base.html
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>
</head>

<body>
 <h1>Hello this is from template basead views</h1>
 <h2>{{name}}</h2>
 <h2>{{city}}</h2>
 <h2>{{marks}}</h2>
 <h2>{{subject}}</h2>

</body>

</html>

classbvs/templates/class2/base1.html
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>
</head>

<body>
 <div>
  {% block body_block %}
  {% endblock %}
 </div>
</body>

</html>

classbvs/templates/class2/book_confirm_delete.html
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>
</head>

<body>
 <h1>Are u Sure to Delete {{book.title}}</h1>
 <form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Delete Record">
  <a href="/">No misteken</a>
 </form>
</body>

</html>

classbvs/templates/class2/book_detail.html
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>
</head>

<body>
 <h1>Book Infrormation</h1>
 <h2>{{book.title}}</h2>
 <h2>{{book.author}}</h2>
 <h2>{{book.pages}}</h2>
 <h2>{{book.price}}</h2>
 <button type="submit"><a href="/">Home</a></button>
 <button type="submit"><a href="/update/{{book.id}}">Update Book</a></button>
 <a href="/delete/{{book.id}}">Delete</a>
</body>

</html>

classbvs/templates/class2/book_form.html
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>
</head>

<body>
 <h1>Book Data Insert/Create Form</h1>
 <form action="" method="POST">
  {{form.as_p}}
  {% csrf_token %}
  <input type="submit" class="btn-btn-lg" value="Insert Book Data">
 </form>
</body>

</html>

classbvs/templates/class2/book_list.html
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Document</title>
</head>

<body>
 <div align='center'>
  <h1>Books Information</h1>

  {% for i in list_of_books %}
  <ul>
   <h1><a href="{{i.id}}">{{i.title}}</a></h1>


  </ul>
  {% endfor %}
  <button type="submit"><a href="/create/">create</a></button>
 </div>
</body>

</html>

classbvs/templates/class2/comany.html
<!DOCTYPE html>
{% extends 'base1.html %}
{% block body_block %}
<h1>List Of All Companyees</h1>
{% for i in company_list %}
<h2><a href="#">{{i.name}}</a></h2>
{% endfor %}
{% endblock %}